
from detectron2.config import CfgNode as CN


def add_tensormask_config(cfg):
    """
    Add config for TensorMask.
    """
    cfg.MODEL.TENSOR_MASK = CN()

    cfg.MODEL.TENSOR_MASK.IN_FEATURES = ["p2", "p3", "p4", "p5", "p6", "p7"]

    cfg.MODEL.TENSOR_MASK.NUM_CONVS = 4

    cfg.MODEL.TENSOR_MASK.NUM_CLASSES = 80
    cfg.MODEL.TENSOR_MASK.CLS_CHANNELS = 256

    cfg.MODEL.TENSOR_MASK.SCORE_THRESH_TEST = 0.05
    cfg.MODEL.TENSOR_MASK.TOPK_CANDIDATES_TEST = 6000
    cfg.MODEL.TENSOR_MASK.NMS_THRESH_TEST = 0.5

    cfg.MODEL.TENSOR_MASK.BBOX_CHANNELS = 128
    cfg.MODEL.TENSOR_MASK.BBOX_REG_WEIGHTS = (1.5, 1.5, 0.75, 0.75)

    cfg.MODEL.TENSOR_MASK.FOCAL_LOSS_GAMMA = 3.0
    cfg.MODEL.TENSOR_MASK.FOCAL_LOSS_ALPHA = 0.3

    cfg.MODEL.TENSOR_MASK.MASK_CHANNELS = 128
    cfg.MODEL.TENSOR_MASK.MASK_LOSS_WEIGHT = 2.0
    cfg.MODEL.TENSOR_MASK.POSITIVE_WEIGHT = 1.5
    cfg.MODEL.TENSOR_MASK.ALIGNED_ON = False
    cfg.MODEL.TENSOR_MASK.BIPYRAMID_ON = False
